source "https://rubygems.org"
ruby ">= 3.4.7"

gem "rails", "~> 7.1"
gem "bcrypt", "~> 3.1"
gem "puma", "~> 6.4"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "propshaft"
gem "bootsnap", require: false

group :development, :test do
  gem "sqlite3", "~> 1.6"
end

group :production do
  gem "pg", "~> 1.5"
end

group :development do
  gem "web-console"
  gem "listen"
end
